### PR TITLE
React 19 fixes

### LINKED ISSUE #695: android - sliding broken on RN 0.79 (rc3)
## Environment

New project initialized with RN 79 rc-3, with new architecture enabled

## Description

https://github.com/user-attachments/assets/ed9f8a3a-af6a-48c3-898c-6f6f1a05545f

## Reproducible Demo

https://github.com/vonovak/slider-bug-79

### LINKED ISSUE #701: findDOMNode usage breaks on React 19 with react-native-web 0.20+
## Environment

```
System:
  OS: macOS 15.3.2
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 48.38 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman:
    version: 2025.04.07.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/caretotranslate/.rvm/gems/ruby-3.3.7/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7621141
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2.1
    path: /usr/local/opt/openjdk/bin/javac
  Ruby:
    version: 3.3.7
    path: /Users/caretotranslate/.rvm/rubies/ruby-3.3.7/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: ^18.0.0
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.0
    wanted: 0.79.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

* are you using the new architecture?
Yes
* which version of react & react-native are you using?
react 19  react-native 0.79.0 and react-native-web 0.20.0

## Description
After upgrading to React 19 and react-native-web@0.20.0, I'm encountering a runtime error when using this library on the web:

```
TypeError: _reactDom.default.findDOMNode is not a function
    at updateContainerPositionX (node_modules/@react-native-community/slider/dist/RNCSliderNativeComponent.web.js:8651)
    at onLayout (node_modules/@react-native-community/slider/dist/RNCSliderNativeComponent.web.js:10920)
    at useElementLayout (node_modules/react-native-web/dist/modules/useElementLayout/index.js:52)
    at UIManager.measure (node_modules/react-native-web/dist/exports/UIManager/index.js:51)
```

## Reproducible Demo

Install react@19, react-dom@19, and react-native-web@0.20.0

Use @react-native-community/slider in a web build

Observe crash at runtime

### PR DESCRIPTION
**Pull request by stephentuso**
Summary:
---------
Fixes #701
Fixes #695

`defaultProps` and `findDOMNode` were removed in React 19.

For `findDOMNode`: it wasn't actually needed, as the ref is already pointed at the element. I added `dom` to the TS libs to support the type, but we can use a ts-ignore if you don't want that.

For `defaultProps`: I moved the values to default parameters in the function component and cleaned up the logic some

Test Plan:
----------

`example-web` is updated to react 19 and fully working now.

I haven't gotten a chance to test this on native yet

### CODE REVIEW

**Comment by smalhotra3599** [comment]
@stephentuso @BartoszKlonowski  any update on when this will get merged and released? This is breaking my app currently and since it seems like you all have a solution, I'd rather just wait for you to handle it then to reimplement the slider all together. Appreciate your help, thanks!

**Comment by stephentuso** [comment]
@smalhotra3599 if it's just the web version you're having issues with, I'm using this patch based on this PR until they merge it https://gist.github.com/stephentuso/4e1daf6aea8489407138addd4c5ceb5d

File: package/src/Slider.tsx [hunk 1]
```diff
@@ -200,34 +200,36 @@ type Props = ViewProps &
   }>;
 
 const SliderComponent = (
-  props: Props,
-  forwardedRef?: Ref<typeof RCTSliderNativeComponent>,
```
Comment (BartoszKlonowski) [inline package/src/Slider.tsx:204]: Can you elaborate on why removing this?

**Review by BartoszKlonowski — COMMENTED** [review]
I am happy to approve it as soon as the matter of removing arguments of `SliderComponent` is resolved. Other than that, good PR. I tested it locally for Android and can confirm it also solves the linked issue.
Thanks for handling that! 👍

File: package/src/Slider.tsx [hunk 2]
```diff
@@ -298,30 +291,36 @@ const SliderComponent = (
...
       <RCTSliderNativeComponent
-        {...localProps}
-        value={value}
+        {...props}
+        minimumValue={minimumValue}
+        maximumValue={maximumValue}
+        step={step}
+        inverted={inverted}
+        tapToSeek={tapToSeek}
+        value={passedValue}
```
Comment (stephentuso) [inline package/src/Slider.tsx:314]: @BartoszKlonowski basically, the props that were being set by `defaultProps` and then passed through `localProps` were these 6 props, which are now being set by the default function parameters and explicitly passed here. The other 2 from `defaultProps`, `lowerLimit` and `upperLimit`, are already passed below

File: package/src/RNCSliderNativeComponent.web.tsx [hunk 3]
```diff
@@ -362,7 +359,8 @@ const RCTSliderWebComponent = React.forwardRef(
         onMoveShouldSetResponder={() => !disabled}
         onResponderGrant={() => onSlidingStart(value)}
         onResponderRelease={onTouchEnd}
-        onResponderMove={onMove}>
+        onResponderMove={onMove}
+      >
```
Comment (BartoszKlonowski) [inline package/src/RNCSliderNativeComponent.web.tsx:363]:
```suggestion
        onResponderMove={onMove}>
```

File: package/src/Slider.tsx [hunk 4]
```diff
@@ -298,30 +291,36 @@ const SliderComponent = (
       onLayout={(event) => {
         setWidth(event.nativeEvent.layout.width);
       }}
-      style={[style, {justifyContent: 'center'}]}>
+      style={[style, {justifyContent: 'center'}]}
+    >
```
Comment (BartoszKlonowski) [inline package/src/Slider.tsx:295]:
```suggestion
      style={[style, {justifyContent: 'center'}]}>
```

File: package/src/Slider.tsx [hunk 5]
```diff
@@ -298,30 +291,36 @@ const SliderComponent = (
...
         upperLimit={upperLimit}
         accessibilityState={_accessibilityState}
         thumbImage={
           Platform.OS === 'web'
             ? props.thumbImage
             : props.StepMarker
-            ? undefined
-            : Image.resolveAssetSource(props.thumbImage)
+              ? undefined
+              : Image.resolveAssetSource(props.thumbImage)
```
Comment (BartoszKlonowski) [inline package/src/Slider.tsx:323]:
```suggestion
            ? undefined
            : Image.resolveAssetSource(props.thumbImage)
```

**Review by BartoszKlonowski — APPROVED** [review]
Thanks for explanations!
Just couple of linter complaints covered, and it's good to go.

**Comment by zbarbuto** [comment]
Thanks for merging - can this fix please be published to npm?

**Comment by qwezey** [comment]
Will be published to npm? This would help out a lot.

**Comment by BartoszKlonowski** [comment]
Dears, @zbarbuto, yes - I plan to release this today, in both v4.5.7 supporting old arch, as well as in default, v5.0.0 supporting new arch only.
Please check the existing pull request and/or releases for more details.
