### PR TITLE
fix(#249): regarding issue introduced in IOS 14 UISlider needs to forc…

### LINKED ISSUE #249: Setting disabled on iOS sometimes does not set disabled style
## Environment

System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 89.49 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/luke/.gem/ruby/2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

If you set the disabled flag on the slider and run on iOS it will sometimes not set/unset the greyed out style. It appears to correctly set the style if you set disabled before first mount, however on an already mounted component setting the flag does not change the visual state (though it does stop it from being editable). Conversely if you have it disabled on mount and set it to disabled={false} after that it retains the disabled style until you change the value in the component.

Everything appears to work correctly in android.

### Initially disabled then re-enabled, doesn't change visual state until value changes.
ezgif-3-32417a5496fe

### Initially enabled, doesn't change visual state when disabled.
ezgif-3-b1e8737e1ffc

Below is my code for the above demo app.

```
const App: () => React$Node = () => {
  const [a, setA] = useState(true);
  const [b, setB] = useState(false);
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <Header />
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
          <View style={styles.body}>
            <Slider
              disabled={a}
              value={0.5}
              style={{
                height: 30,
              }}
            />
            <Button onPress={() => setA(!a)} title="Toggle slider" />
            <Slider
              disabled={b}
              value={0.5}
              style={{
                height: 30,
              }}
            />
            <Button onPress={() => setB(!b)} title="Toggle slider" />
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};
```

### PR DESCRIPTION
**Pull request by MateWW**
Closes #249

Summary:
---------
Fixes issue mentioned in this article and reported in #249 
https://developer.apple.com/forums/thread/658526

Test Plan:
----------

1. Use reproducible code from #249
2. Tap multiple times on disable button

https://user-images.githubusercontent.com/16048381/198872127-0a211628-7bf6-4736-8e3b-a4d54d54f224.mov

### CODE REVIEW

File: package/ios/RNCSliderComponentView.mm [hunk 1]
```diff
@@ -152,7 +152,7 @@ - (void)updateProps:(const Props::Shared &)props oldProps:(const Props::Shared &
         }
     }
     if (oldScreenProps.disabled != newScreenProps.disabled) {
-        slider.enabled = !newScreenProps.disabled;
+        [view setDisabled: newScreenProps.disabled];
```
Comment (BartoszKlonowski) [inline package/ios/RNCSliderComponentView.mm:155]:
```suggestion
        [slider setDisabled: newScreenProps.disabled];
```
`RNCSliderComponentView` gets compiled for new architecture which is why the CI fails for Fabric iOS.

File: package/ios/RNCSlider.m [hunk 2]
```diff
@@ -132,6 +132,13 @@ - (void)setInverted:(BOOL)inverted
   }
 }
 
+- (void)setDisabled:(BOOL)disabled
+{
+    self.enabled = !disabled;
+    // ISSUE:
```
Comment (BartoszKlonowski) [inline package/ios/RNCSlider.m:138]: ✂️ 
Let's use git history for such information

File: package/ios/RNCSlider.h [hunk 3]
```diff
@@ -28,5 +28,6 @@
 @property (nonatomic, strong) NSArray *accessibilityIncrements;
 
 - (float) discreteValue:(float)value;
+- (void) setDisabled:(bool)disabled;
```
Comment (BartoszKlonowski) [inline package/ios/RNCSlider.h:31]: This will throw a warning for new architecture as we only have this method implemented for old arch, but we are doing the same with `discreteValue` so let's ignore that for now.

**Review by BartoszKlonowski — COMMENTED** [review]
Thank you for taking care of that, @MateWW!
Just a couple tweaks and I'll be happy to merge it 👍

**Review by BartoszKlonowski — APPROVED** [review]
@MateWW I allowed myself to apply the changes to push the topic forward.
Thanks again for this 👍

**Comment by MateWW** [comment]
> @MateWW I allowed myself to apply the changes to push the topic forward.
> 
> Thanks again for this 👍 

Sorry for late replay. I wanted to handle that during the weekend
