### PR TITLE
fix(web): fix issues preventing web implementation from working

### LINKED ISSUE #436: How to / can use this library on web projects?
Hello, it is not clear to me if whether react-native-slider has web support, the docs do say
> For web support please use @react-native-community/slider@next

When I try to use the component with react-native-web I stumble into this issue https://github.com/callstack/react-native-slider/issues/185.

I see that you have a component built specifically for web [RNCSliderNativeComponent.web.tsx](https://github.com/callstack/react-native-slider/blob/main/package/src/RNCSliderNativeComponent.web.tsx) but I don't see any documentation in regards to it, neither do I see that the source code checks which component to use when Slider is imported like so: `import Slider from '@react-native-community/slider';`.

Should the developer decide which component to import? and is `.web` component actively being maintained?

Would adding a [`browser`](https://github.com/defunctzombie/package-browser-field-spec) field to package.json that points to the `RNCSliderNativeComponent.web` component be a possible solution? it seemed to do the trick when I added it on my local machine.

appreciate the hard work and thanks in advance for your help 🙏

### PR DESCRIPTION
**Pull request by jspizziri**
Summary:
---------
This pull request fixes #436 , #438, #352, #355, #344

This PR:

1. Gets the web implementation working in a minimal form.
2. Adds animations to slider interactions.
4. Adds an `example-web` folder containing a functional web version of the project for web demo/testing
4. Fixes known outstanding issues with the web implementation (i.e. disabled sliders, thumbImages, etc).

Test Plan:
----------

I created an `example-web` folder containing a web version that mirrors the existing `example`.

### CODE REVIEW

**Comment by jspizziri** [comment]
https://github.com/callstack/react-native-slider/issues/436

**Comment by jspizziri** [comment]
Just fixed the linter errors.

**Comment by jspizziri** [comment]
@BartoszKlonowski I've added two new commits:

1. Adds animation to the slider position on web (before it would only re-render on drag end)
2. Adds an example web project for demonstration and testing purposes.

Let me know if this is too large for a single commit. The initial commit is all that's necessary to get web minimally working. The other two are just enhancements.

Would love to get this merged and released as soon as possible so let me know what I can do on my side to make that happen.

**Comment by BartoszKlonowski** [comment]
Hello @jspizziri!
What's most important: Thank you very much for this effort and the PR, I really super appreciate it!
Second: No need to rush - I plan to release v4.4.0 by the end of this week with the `minimumLimit` and `maximumLimit` feature for mobiles, so I'll be super happy to include your work in this version 👍 
Again, many thanks - I already started reviewing and I'm about to test it a bit.

**Comment by jspizziri** [comment]
@BartoszKlonowski awesome. I'm also in the process of making the `example-web` mirror the `example` with all it's various test cases.

**Comment by jspizziri** [comment]
I've found a few bugs now that I implemented all the test examples. Working on fixing those now.

**Comment by jspizziri** [comment]
@BartoszKlonowski I fixed a bug in contexts when `value` was not controlled externally (see the change to `useLayoutEffect`). 

Lastly, there's a bug with `disabled` sliders. For some reason, `onStartShouldSetResponder` and `onMoveShouldSetResponder` are just not working. They're not even being called and I haven't been able to figure it out.

File: example-web/src/index.tsx [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+import './index.css';
+import App from './App';
+import reportWebVitals from './reportWebVitals';
+
+const root = ReactDOM.createRoot(
+  document.getElementById('root') as HTMLElement
+);
+root.render(
+  <React.StrictMode>
+    <App />
```
Comment (BartoszKlonowski) [inline example-web/src/index.tsx:12]: I'm having issues running the example app for web.
I launch it by following the README step by step, but all I see is the empty page.

Comment (BartoszKlonowski) [reply example-web/src/index.tsx:12]: I'm able to display the Slider if I just simplify the `<App/>` to render the `SliderExample` only, but this rendered Slider disappears as soon as there's any interaction with it.

Comment (jspizziri) [reply example-web/src/index.tsx:12]: Hmmm, that's quite interesting. Let me see if I can recreate that by wiping my project folder entirely and rebuilding.

Are you getting any console errors when you see the whitescreen?

Comment (BartoszKlonowski) [reply example-web/src/index.tsx:12]: No errors at all, but I can see that the server works well. It renders whatever I code and throws the error if I intentionally break something.
Also, I rendered the very basic example of Slider, and it does render, but the Slider cannot be interacted with - it just won't move. Let me try it using a different web browser, though...

Comment (jspizziri) [reply example-web/src/index.tsx:12]: Yeah, it might be a browser polyfill issue. I'm working on Brave (Chrome/Chromium) and it seems to work there. What browser are you on?

Comment (BartoszKlonowski) [reply example-web/src/index.tsx:12]: Aah, I see it - it's just the package that I had already built in `dist/`, but it required full rebuild. Sorry for confusion!

**Comment by jspizziri** [comment]
@BartoszKlonowski to my knowledge, this PR now addresses all the outstanding web issues.

**Comment by BartoszKlonowski** [comment]
> @BartoszKlonowski to my knowledge, this PR now addresses all the outstanding web issues.

Except for #355 which on my side looks like a still valid issue. I indeed see you added this feature (thanks!) but I have a hard time displaying it using the demo app.

**Comment by BartoszKlonowski** [comment]
> @BartoszKlonowski did you make sure to pull everything and rebuild the package?

Let me do that again, in case I forgot to do so again...

File: example-web/README.md [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+
+This example project can be used to test/demo this project in the context of
+`react-native-web`. Here's how to use it:
+
+1. Build the library:
+    ```sh
+    # go to the `package` folder
+    cd ../package
+    # build the library
+    yarn prepare
```
Comment (BartoszKlonowski) [inline example-web/README.md:15]: I can see this PR delivers both `package-lock.json` as well as `yarn.lock`.
In this project we use npm as it is more strict and we want to make sure that the package installs correctly using it.
Would it be possible to change it to `npm run prepare` and remove `yarn.lock`, or maybe there are reasons behind having `yarn` here?

File: example-web/README.md [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+    # go back to the example
+    cd ../example-web
+    ```
+2. Run the dev server:
+    ```sh
+    yarn start
```
Comment (BartoszKlonowski) [inline example-web/README.md:21]: Let me leave a comment here just in case we agree to use npm: `npm start`

File: example-web/src/App.test.tsx [hunk 4]
```diff
@@ -0,0 +1,9 @@
+import React from 'react';
+import { render, screen } from '@testing-library/react';
+import App from './App';
+
+test('renders learn react link', () => {
+  render(<App />);
+  const linkElement = screen.getByText(/learn react/i);
+  expect(linkElement).toBeInTheDocument();
```
Comment (BartoszKlonowski) [inline example-web/src/App.test.tsx:8]: This will obviously fail, so I wonder whether we should just remove the tests or go with the simple `toMatchSnapshot` test only to keep it vital.

**Comment by jspizziri** [comment]
@BartoszKlonowski great news. Is there anything else you need me to do to get this across the finish line?

**Review by BartoszKlonowski — APPROVED** [review]
This looks very well 👍 
I just left two very minor comments, but still: Thank you for this!

File: example-web/src/App.test.tsx (hunk 4 above)
Comment (jspizziri) [reply example-web/src/App.test.tsx:8]: This is just the standard test generated by create-react-app. I'll remove it.

**Comment by jspizziri** [comment]
@BartoszKlonowski just pushed the changes that incorporate your feedback.

File: package/src/RNCSliderNativeComponent.web.tsx [hunk 5]
```diff
@@ -2,24 +2,22 @@
...
   View,
   StyleSheet,
   ColorValue,
   ViewStyle,
-  NativeSyntheticEvent,
   GestureResponderEvent,
   LayoutChangeEvent,
+  Image,
 } from 'react-native';
+import type {ImageSource} from 'react-native/Libraries/Image/ImageSource';
```
Comment (BartoszKlonowski) [inline package/src/RNCSliderNativeComponent.web.tsx:14]:
```suggestion
//@ts-ignore
import type {ImageSource} from 'react-native/Libraries/Image/ImageSource';
```

**Comment by landabaso** [comment]
Hi @jspizziri, thank you for your contributions to the web portion of react-native-slider! I've recently posted an issue regarding the differing behavior of onValueChange on web platforms. Seeing your work, it seems you might have insights into this matter. I'd greatly appreciate your thoughts on it. Thanks!
https://github.com/callstack/react-native-slider/issues/562
